### ISSUE TITLE
Inline models not working for responses

### ISSUE THREAD

**Issue by jjmartin** [awslabs/aws-apigateway-swagger-importer#113]
if i do a create and then immediately update without making any changes to the json, i am getting an error:

```
...
2015-12-07 09:10:01,573 INFO - Creating method parameter for api yu5ia25r54 and method GET with name method.request.path.customerCommonId
2015-12-07 09:10:01,646 INFO - Creating method parameter for api yu5ia25r54 and method GET with name method.request.querystring.startDate
2015-12-07 09:10:01,722 INFO - Creating method parameter for api yu5ia25r54 and method GET with name method.request.querystring.endDate
2015-12-07 09:10:01,794 INFO - Creating integration with type AWS
2015-12-07 09:10:02,170 INFO - Cleaning up removed methods
2015-12-07 09:10:02,301 INFO - Cleaning up removed resources
2015-12-07 09:10:02,442 INFO - Removing deleted model invoicedetails
2015-12-07 09:10:02,510 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.ConflictException: Cannot delete model 'invoicedetails', is referenced in method response: /invoice-details/{customerCommonId}/GET (Service: null; Status Code: 409; Error Code: null; Request ID: fa1f6079-9cfc-11e5-9dfe-5351371808b8)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1275)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:873)
```

so far this is a fairly simple api with just one path to a GET...

**Comment by rpgreen** [comment]
This looks like an issue that was fixed recently - are you on the latest version?

**Comment by jjmartin** [comment]
i have the latest master... 
i got around the issue by removing the schema key from my responses/200 section of the swagger.
when i put it back and run the update, I still get this error.

**Comment by jjmartin** [comment]
to make my swagger.json run again, i have to remove that schema section then, manually delete the reference to the model in the Method Response/200 HTTP Status, then manually delete the model

**Comment by rpgreen** [comment]
Can you send your swagger file so we can try to reproduce?

**Comment by rpgreen** [comment]
Also - silly question but did you run 'mvn assembly:assembly' after pulling the latest code?

**Comment by jjmartin** [comment]
yea... i did the `mvn assembly:assembly`

will send swagger that has the effect.

**Comment by joshua-peterson-volusion** [comment]
I'm seeing this as well.  The importer appears to be trying to delete models that are still in use.

**Comment by rpgreen** [comment]
There's a bug here. We will look into a solution.

There's an easy workaround, which is to use a model reference for your responses, rather than inline models, like this:

```
                    "200": {
                         "schema": {
                            "$ref": "#/definitions/myModel"
                         }
                    },
```

**Comment by BryanCrotaz** [comment]
PR #100 should fix this - or at least it is intended to

**Comment by BryanCrotaz** [comment]
Is this a duplicate of issue #99?

**Comment by rpgreen** [comment]
Should be fixed now
