### ISSUE TITLE
ConflictException: Resource with id 'xwdshi' has a conflicting path

### ISSUE THREAD

**Issue by sbacquie-carecloud** [awslabs/aws-apigateway-swagger-importer#15]
When trying to import, I keep getting the following error, on different end points each time:

```
2015-08-11 08:44:53,074 ERROR - Error creating API, rolling back
com.amazonaws.services.apigateway.model.ConflictException: Resource with id 'xwdshi' has a conflicting path (Service: null; Status Code: 409; Error Code: null; Request ID: 7655b030-4026-11e5-a041-b1519f2f7bca)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:117)
    at com.sun.proxy.$Proxy29.createResource(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResource(ApiGatewaySdkSwaggerApiImporter.java:155)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResource(ApiGatewaySdkSwaggerApiImporter.java:314)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:253)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:90)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:101)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)
2015-08-11 08:44:53,075 INFO - Deleting API zmum9bq57a
2015-08-11 08:44:55,755 ERROR - Error importing API from Swagger
com.amazonaws.services.apigateway.model.ConflictException: Resource with id 'xwdshi' has a conflicting path (Service: null; Status Code: 409; Error Code: null; Request ID: 7655b030-4026-11e5-a041-b1519f2f7bca)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.postResource(HalClient.java:98)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:117)
    at com.sun.proxy.$Proxy29.createResource(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResource(ApiGatewaySdkSwaggerApiImporter.java:155)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResource(ApiGatewaySdkSwaggerApiImporter.java:314)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createResources(ApiGatewaySdkSwaggerApiImporter.java:253)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.createApi(ApiGatewaySdkSwaggerApiImporter.java:90)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.importApi(ApiGatewaySwaggerFileImporter.java:48)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:101)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)
```

I can provide a Swagger file to reproduce it if necessary.

**Comment by sbacquie-carecloud** [comment]
I actually have a generic example that produces it as well, so I'll paste it here:

``` json
{
  "swagger": "2.0",
  "info": {
    "title": "Conflict Error Example",
    "description": "This will produce a conflicting path error",
    "version": "2.0.0"
  },
  "schemes": [
    "http"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/v1/owls": {
      "get": {
        "responses": {
          "200": {
            "description": "test placeholder"
          }
        },
        "parameters": [
          {
            "name": "authentication",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://testapi12345.net/",
          "httpMethod": "GET",
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    },
    "/v1/owls/{id}/beaks": {
      "get": {
        "responses": {
          "200": {
            "description": "test placeholder"
          }
        },
        "parameters": [
          {
            "name": "authentication",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://testapi12345.net/",
          "httpMethod": "GET",
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    },
    "/v1/owls/{id}/beaks/{type}": {
      "get": {
        "responses": {
          "200": {
            "description": "test placeholder"
          }
        },
        "parameters": [
          {
            "name": "authentication",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "type",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://testapi12345.net/",
          "httpMethod": "GET",
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    },
    "/v2/owls/ridiculously/long/path/for/testing/purposes": {
      "get": {
        "responses": {
          "200": {
            "description": "test placeholder"
          }
        },
        "parameters": [
          {
            "name": "authentication",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://testapi12345.net/",
          "httpMethod": "GET",
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    },
    "/v2/owls/{id}/beaks/ridiculously/long/path/for/testing/purposes": {
      "get": {
        "responses": {
          "200": {
            "description": "test placeholder"
          }
        },
        "parameters": [
          {
            "name": "authentication",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://testapi12345.net/",
          "httpMethod": "GET",
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    },
    "/v2/owls/{id}/beaks/{type}/ridiculously/long/path/for/testing/purposes": {
      "get": {
        "responses": {
          "200": {
            "description": "test placeholder"
          }
        },
        "parameters": [
          {
            "name": "authentication",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "type",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://testapi12345.net/",
          "httpMethod": "GET",
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    },
    "/v3/owls": {
      "get": {
        "responses": {
          "200": {
            "description": "test placeholder"
          }
        },
        "parameters": [
          {
            "name": "authentication",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://testapi12345.net/",
          "httpMethod": "GET",
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    },
    "/v3/owls/{id}/beaks": {
      "get": {
        "responses": {
          "200": {
            "description": "test placeholder"
          }
        },
        "parameters": [
          {
            "name": "authentication",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://testapi12345.net/",
          "httpMethod": "GET",
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    },
    "/v3/owls/{id}/beaks/{type}": {
      "get": {
        "responses": {
          "200": {
            "description": "test placeholder"
          }
        },
        "parameters": [
          {
            "name": "authentication",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "type",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://testapi12345.net/",
          "httpMethod": "GET",
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    },
    "/v4/owls": {
      "get": {
        "responses": {
          "200": {
            "description": "test placeholder"
          }
        },
        "parameters": [
          {
            "name": "authentication",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://testapi12345.net/",
          "httpMethod": "GET",
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    },
    "/v4/owls/{id}/beaks": {
      "get": {
        "responses": {
          "200": {
            "description": "test placeholder"
          }
        },
        "parameters": [
          {
            "name": "authentication",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://testapi12345.net/",
          "httpMethod": "GET",
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    },
    "/v4/owls/{id}/beaks/{type}": {
      "get": {
        "responses": {
          "200": {
            "description": "test placeholder"
          }
        },
        "parameters": [
          {
            "name": "authentication",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "type",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://testapi12345.net/",
          "httpMethod": "GET",
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    },
    "/v4/owls/ridiculously/long/path/for/testing/purposes": {
      "get": {
        "responses": {
          "200": {
            "description": "test placeholder"
          }
        },
        "parameters": [
          {
            "name": "authentication",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://testapi12345.net/",
          "httpMethod": "GET",
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    },
    "/v4/owls/{id}/beaks/ridiculously/long/path/for/testing/purposes": {
      "get": {
        "responses": {
          "200": {
            "description": "test placeholder"
          }
        },
        "parameters": [
          {
            "name": "authentication",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://testapi12345.net/",
          "httpMethod": "GET",
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    },
    "/v4/owls/{id}/beaks/{type}/ridiculously/long/path/for/testing/purposes": {
      "get": {
        "responses": {
          "200": {
            "description": "test placeholder"
          }
        },
        "parameters": [
          {
            "name": "authentication",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "type",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://testapi12345.net/",
          "httpMethod": "GET",
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    }
  }
}
```

**Comment by rpgreen** [comment]
Thanks. Your Swagger file looks good to me. We will investigate this on the
service side and get back to you.

On Tuesday, August 11, 2015, sbacquie-carecloud notifications@github.com
wrote:

> I actually have a generic example that produces it as well, so I'll paste
> it here:
> 
> {
>   "swagger": "2.0",
>   "info": {
>     "title": "Conflict Error Example",
>     "description": "This will produce a conflicting path error",
>     "version": "2.0.0"
>   },
>   "schemes": [
>     "http"
>   ],
>   "produces": [
>     "application/json"
>   ],
>   "paths": {
>     "/v1/owls": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "test placeholder"
>           }
>         },
>         "parameters": [
>           {
>             "name": "authentication",
>             "in": "query",
>             "required": true,
>             "type": "string"
>           }
>         ],
>         "x-amazon-apigateway-integration": {
>           "type": "http",
>           "uri": "https://testapi12345.net/",
>           "httpMethod": "GET",
>           "responses": {
>             "200": {
>               "statusCode": "200"
>             }
>           }
>         }
>       }
>     },
>     "/v1/owls/{id}/beaks": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "test placeholder"
>           }
>         },
>         "parameters": [
>           {
>             "name": "authentication",
>             "in": "query",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "id",
>             "in": "path",
>             "required": true,
>             "type": "string"
>           }
>         ],
>         "x-amazon-apigateway-integration": {
>           "type": "http",
>           "uri": "https://testapi12345.net/",
>           "httpMethod": "GET",
>           "responses": {
>             "200": {
>               "statusCode": "200"
>             }
>           }
>         }
>       }
>     },
>     "/v1/owls/{id}/beaks/{type}": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "test placeholder"
>           }
>         },
>         "parameters": [
>           {
>             "name": "authentication",
>             "in": "query",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "id",
>             "in": "path",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "type",
>             "in": "path",
>             "required": true,
>             "type": "string"
>           }
>         ],
>         "x-amazon-apigateway-integration": {
>           "type": "http",
>           "uri": "https://testapi12345.net/",
>           "httpMethod": "GET",
>           "responses": {
>             "200": {
>               "statusCode": "200"
>             }
>           }
>         }
>       }
>     },
>     "/v2/owls/ridiculously/long/path/for/testing/purposes": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "test placeholder"
>           }
>         },
>         "parameters": [
>           {
>             "name": "authentication",
>             "in": "query",
>             "required": true,
>             "type": "string"
>           }
>         ],
>         "x-amazon-apigateway-integration": {
>           "type": "http",
>           "uri": "https://testapi12345.net/",
>           "httpMethod": "GET",
>           "responses": {
>             "200": {
>               "statusCode": "200"
>             }
>           }
>         }
>       }
>     },
>     "/v2/owls/{id}/beaks/ridiculously/long/path/for/testing/purposes": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "test placeholder"
>           }
>         },
>         "parameters": [
>           {
>             "name": "authentication",
>             "in": "query",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "id",
>             "in": "path",
>             "required": true,
>             "type": "string"
>           }
>         ],
>         "x-amazon-apigateway-integration": {
>           "type": "http",
>           "uri": "https://testapi12345.net/",
>           "httpMethod": "GET",
>           "responses": {
>             "200": {
>               "statusCode": "200"
>             }
>           }
>         }
>       }
>     },
>     "/v2/owls/{id}/beaks/{type}/ridiculously/long/path/for/testing/purposes": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "test placeholder"
>           }
>         },
>         "parameters": [
>           {
>             "name": "authentication",
>             "in": "query",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "id",
>             "in": "path",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "type",
>             "in": "path",
>             "required": true,
>             "type": "string"
>           }
>         ],
>         "x-amazon-apigateway-integration": {
>           "type": "http",
>           "uri": "https://testapi12345.net/",
>           "httpMethod": "GET",
>           "responses": {
>             "200": {
>               "statusCode": "200"
>             }
>           }
>         }
>       }
>     },
>     "/v3/owls": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "test placeholder"
>           }
>         },
>         "parameters": [
>           {
>             "name": "authentication",
>             "in": "query",
>             "required": true,
>             "type": "string"
>           }
>         ],
>         "x-amazon-apigateway-integration": {
>           "type": "http",
>           "uri": "https://testapi12345.net/",
>           "httpMethod": "GET",
>           "responses": {
>             "200": {
>               "statusCode": "200"
>             }
>           }
>         }
>       }
>     },
>     "/v3/owls/{id}/beaks": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "test placeholder"
>           }
>         },
>         "parameters": [
>           {
>             "name": "authentication",
>             "in": "query",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "id",
>             "in": "path",
>             "required": true,
>             "type": "string"
>           }
>         ],
>         "x-amazon-apigateway-integration": {
>           "type": "http",
>           "uri": "https://testapi12345.net/",
>           "httpMethod": "GET",
>           "responses": {
>             "200": {
>               "statusCode": "200"
>             }
>           }
>         }
>       }
>     },
>     "/v3/owls/{id}/beaks/{type}": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "test placeholder"
>           }
>         },
>         "parameters": [
>           {
>             "name": "authentication",
>             "in": "query",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "id",
>             "in": "path",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "type",
>             "in": "path",
>             "required": true,
>             "type": "string"
>           }
>         ],
>         "x-amazon-apigateway-integration": {
>           "type": "http",
>           "uri": "https://testapi12345.net/",
>           "httpMethod": "GET",
>           "responses": {
>             "200": {
>               "statusCode": "200"
>             }
>           }
>         }
>       }
>     },
>     "/v4/owls": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "test placeholder"
>           }
>         },
>         "parameters": [
>           {
>             "name": "authentication",
>             "in": "query",
>             "required": true,
>             "type": "string"
>           }
>         ],
>         "x-amazon-apigateway-integration": {
>           "type": "http",
>           "uri": "https://testapi12345.net/",
>           "httpMethod": "GET",
>           "responses": {
>             "200": {
>               "statusCode": "200"
>             }
>           }
>         }
>       }
>     },
>     "/v4/owls/{id}/beaks": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "test placeholder"
>           }
>         },
>         "parameters": [
>           {
>             "name": "authentication",
>             "in": "query",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "id",
>             "in": "path",
>             "required": true,
>             "type": "string"
>           }
>         ],
>         "x-amazon-apigateway-integration": {
>           "type": "http",
>           "uri": "https://testapi12345.net/",
>           "httpMethod": "GET",
>           "responses": {
>             "200": {
>               "statusCode": "200"
>             }
>           }
>         }
>       }
>     },
>     "/v4/owls/{id}/beaks/{type}": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "test placeholder"
>           }
>         },
>         "parameters": [
>           {
>             "name": "authentication",
>             "in": "query",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "id",
>             "in": "path",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "type",
>             "in": "path",
>             "required": true,
>             "type": "string"
>           }
>         ],
>         "x-amazon-apigateway-integration": {
>           "type": "http",
>           "uri": "https://testapi12345.net/",
>           "httpMethod": "GET",
>           "responses": {
>             "200": {
>               "statusCode": "200"
>             }
>           }
>         }
>       }
>     },
>     "/v4/owls/ridiculously/long/path/for/testing/purposes": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "test placeholder"
>           }
>         },
>         "parameters": [
>           {
>             "name": "authentication",
>             "in": "query",
>             "required": true,
>             "type": "string"
>           }
>         ],
>         "x-amazon-apigateway-integration": {
>           "type": "http",
>           "uri": "https://testapi12345.net/",
>           "httpMethod": "GET",
>           "responses": {
>             "200": {
>               "statusCode": "200"
>             }
>           }
>         }
>       }
>     },
>     "/v4/owls/{id}/beaks/ridiculously/long/path/for/testing/purposes": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "test placeholder"
>           }
>         },
>         "parameters": [
>           {
>             "name": "authentication",
>             "in": "query",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "id",
>             "in": "path",
>             "required": true,
>             "type": "string"
>           }
>         ],
>         "x-amazon-apigateway-integration": {
>           "type": "http",
>           "uri": "https://testapi12345.net/",
>           "httpMethod": "GET",
>           "responses": {
>             "200": {
>               "statusCode": "200"
>             }
>           }
>         }
>       }
>     },
>     "/v4/owls/{id}/beaks/{type}/ridiculously/long/path/for/testing/purposes": {
>       "get": {
>         "responses": {
>           "200": {
>             "description": "test placeholder"
>           }
>         },
>         "parameters": [
>           {
>             "name": "authentication",
>             "in": "query",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "id",
>             "in": "path",
>             "required": true,
>             "type": "string"
>           },
>           {
>             "name": "type",
>             "in": "path",
>             "required": true,
>             "type": "string"
>           }
>         ],
>         "x-amazon-apigateway-integration": {
>           "type": "http",
>           "uri": "https://testapi12345.net/",
>           "httpMethod": "GET",
>           "responses": {
>             "200": {
>               "statusCode": "200"
>             }
>           }
>         }
>       }
>     }
>   }
> }
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-swagger-importer/issues/15#issuecomment-129867350
> .

##

**Comment by cfair** [comment]
This issue, I believe, is solved by my pull request. Since the aws api only returns 25 resources, odds are high that one of your resources doesn't come back with the request, so the api importer tries to create something that already exists.

**Comment by sbacquie-carecloud** [comment]
Yes, I believe so as well.

I'm running your pagination branch against the JSON I provided, and it doesn't error out, but after a while it just hangs and stops importing.

**Comment by rpgreen** [comment]
Thanks for the help @cfair. I have merged in your changes with some modifications. @sbacquie-carecloud please pull and confirm

**Comment by sbacquie-carecloud** [comment]
After pulling the latest code, I'm getting the same behavior as in my previous comment. No error, but the importer hangs indefinitely and the import never finishes.

**Comment by rpgreen** [comment]
At what point does it appear to hang? What's the last log message?

**Comment by sbacquie-carecloud** [comment]
It seems to hang when creating a method. When I run it through Eclipse in Debug mode, and then hit Pause after it hangs, it seems to be stuck on sleep(). Here are the last few log messages:

```
2015-08-11 15:07:22,770 INFO - Creating method parameter for api 5cfck3i83l and method GET with name method.request.querystring.authentication
2015-08-11 15:07:22,833 INFO - Creating integration with type HTTP
2015-08-11 15:07:23,023 INFO - Creating method for api id 5cfck3i83l and resource id s9o3n7 with method get
2015-08-11 15:07:25,668 INFO - Creating resource '{id}' with parent 'owls'
2015-08-11 15:07:27,031 INFO - Creating resource 'beaks' with parent '{id}'
2015-08-11 15:07:27,754 INFO - Creating method response for api 5cfck3i83l and method GET and status 200
2015-08-11 15:07:27,893 INFO - Creating method parameter for api 5cfck3i83l and method GET with name method.request.querystring.authentication
2015-08-11 15:07:27,952 INFO - Creating method parameter for api 5cfck3i83l and method GET with name method.request.path.id
2015-08-11 15:07:28,013 INFO - Creating integration with type HTTP
2015-08-11 15:07:28,197 INFO - Creating method for api id 5cfck3i83l and resource id fd5crr with method get
2015-08-11 15:07:32,243 INFO - Creating resource 'ridiculously' with parent 'beaks'
2015-08-11 15:07:33,577 INFO - Creating resource 'long' with parent 'ridiculously'
2015-08-11 15:07:34,920 INFO - Creating resource 'path' with parent 'long'
2015-08-11 15:07:36,260 INFO - Creating resource 'for' with parent 'path'
2015-08-11 15:07:37,587 INFO - Creating resource 'testing' with parent 'for'
2015-08-11 15:07:38,934 INFO - Creating resource 'purposes' with parent 'testing'
2015-08-11 15:07:39,657 INFO - Creating method response for api 5cfck3i83l and method GET and status 200
2015-08-11 15:07:39,809 INFO - Creating method parameter for api 5cfck3i83l and method GET with name method.request.querystring.authentication
2015-08-11 15:07:39,875 INFO - Creating method parameter for api 5cfck3i83l and method GET with name method.request.path.id
2015-08-11 15:07:39,937 INFO - Creating integration with type HTTP
2015-08-11 15:07:40,126 INFO - Creating method for api id 5cfck3i83l and resource id dqa1ux with method get
2015-08-11 15:07:46,631 INFO - Creating resource '{type}' with parent 'beaks'
2015-08-11 15:07:47,992 INFO - Creating method response for api 5cfck3i83l and method GET and status 200
2015-08-11 15:07:48,123 INFO - Creating method parameter for api 5cfck3i83l and method GET with name method.request.querystring.authentication
2015-08-11 15:07:48,181 INFO - Creating method parameter for api 5cfck3i83l and method GET with name method.request.path.id
2015-08-11 15:07:48,269 INFO - Creating method parameter for api 5cfck3i83l and method GET with name method.request.path.type
2015-08-11 15:07:48,361 INFO - Creating integration with type HTTP
2015-08-11 15:07:48,556 INFO - Creating method for api id 5cfck3i83l and resource id wi1b89 with method get
```

**Comment by sbacquie-carecloud** [comment]
https://github.com/awslabs/aws-apigateway-swagger-importer/blob/master/src/com/amazonaws/service/apigateway/importer/impl/sdk/ApiGatewaySdkSwaggerApiImporter.java#L658-L662

It seems to get stuck in an endless loop right there. The condition in the while loop is always true.

Should I open a new issue?

**Comment by sbacquie-carecloud** [comment]
https://github.com/awslabs/aws-apigateway-swagger-importer/blob/master/src/com/amazonaws/service/apigateway/importer/impl/sdk/ApiGatewaySdkSwaggerApiImporter.java#L659

I changed that line to:

```
resources = resources.getNext();
```

And it seems to work fine now.

**Comment by rpgreen** [comment]
Good catch - this is fixed now

**Comment by shraddhabhata** [comment]
I am still getting the error

Resource with id 'dladxj' has a conflicting path (Service: null; Status Code: 400; Error Code: null; Request ID: 5ff14a90-8302-11e5-9c20-a7b0452cd4d8)

Any pointers?

**Comment by koxon** [comment]
You have conflicting endpoints:

This for example would create a conflict
/events/users/
/events/{event_id}

You could do the following to solve it:
/events/users/
/events?event_id={event_id}

best
ᐧ

On Wed, Nov 4, 2015 at 9:48 AM, shraddhabhata notifications@github.com
wrote:

> I am still getting the error
> 
> Resource with id 'dladxj' has a conflicting path (Service: null; Status
> Code: 400; Error Code: null; Request ID:
> 5ff14a90-8302-11e5-9c20-a7b0452cd4d8)
> 
> Any pointers?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-importer/issues/15#issuecomment-153749607
> .

## 

Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.
