### ISSUE TITLE
API update fails when model is not in use anymore

### ISSUE THREAD

**Issue by banzsh** [awslabs/aws-apigateway-swagger-importer#90]
Hi all,

I got this schema to be imported using the tool:

``` json
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "DummyAPI"
  },
  "basePath": "/v1",
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/auth/login": {
      "x-swagger-router-controller": "authController",
      "post": {
        "operationId": "login",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
                "$ref": "#/definitions/AuthInput"
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "properties": {}
            }
          }
        },
        "x-amazon-apigateway-integration": {
          "type": "HTTP",
          "httpMethod": "post",
          "uri": "https://example.com/v1/auth/login",
          "requestParameters": {},
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AuthInput": {
      "required": [
        "email"
      ],
      "properties": {
        "email": {
          "type": "string"
        }
      }
    }
  }
}
```

Importing goes well but when I try to update the API with new schema that has the model removed, exception occures:

```
2015-11-20 18:48:58,098 INFO - Attempting to update API from Swagger definition. API identifier: f3n5471jmd Swagger file: ../swagger.json
reading from ../swagger.json
2015-11-20 18:48:58,169 WARN - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null}
2015-11-20 18:48:58,170 INFO - Parsed Swagger with 1 paths
2015-11-20 18:48:58,737 INFO - Removing deleted model AuthInput
2015-11-20 18:48:58,918 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.ConflictException: Cannot delete model 'AuthInput', is referenced in method request: /v1/auth/login/POST (Service: null; Status Code: 409; Error Code: null; Request ID: 9594adbd-8fa6-11e5-bb65-4f55e07ff182)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1239)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:823)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.deleteResource(HalClient.java:142)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:129)
    at com.sun.proxy.$Proxy33.deleteModel(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.lambda$cleanupModels$2(ApiGatewaySdkApiImporter.java:145)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.cleanupModels(ApiGatewaySdkApiImporter.java:143)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateModels(ApiGatewaySdkSwaggerApiImporter.java:394)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateApi(ApiGatewaySdkSwaggerApiImporter.java:82)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.updateApi(ApiGatewaySwaggerFileImporter.java:58)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:143)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:74)

```

Second schema follows: 

``` json
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "DummyAPI"
  },
  "basePath": "/v1",
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/auth/login": {
      "x-swagger-router-controller": "authController",
      "post": {
        "operationId": "login",
        "parameters": [
          {
            "name": "email",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "properties": {}
            }
          }
        },
        "x-amazon-apigateway-integration": {
          "type": "HTTP",
          "httpMethod": "post",
          "uri": "https://example.com/v1/auth/login",
          "requestParameters": {},
          "responses": {
            "200": {
              "statusCode": "200"
            }
          }
        }
      }
    }
  },
  "definitions": {}
}
```

As I can see the tool tries to process models before paths thus having this exception raised for trying to remove a model before updating the path that is not using it anymore.

Is anything wrong with the schemas or it is an actual issue.

Thank you!

**Comment by Sam-Martin** [comment]
:+1: 
I have the same issue.  
It seems like `cleanupModels` in [ApiGatewaySdkApiImporter.java](https://github.com/awslabs/aws-apigateway-importer/blob/5ddb61b67205b383099bf324cf100ebdbde31988/src/com/amazonaws/service/apigateway/importer/impl/sdk/ApiGatewaySdkApiImporter.java) is erroneously deleting models which still exist.

**Comment by mr337** [comment]
Getting bitten by this too, currently having to delete and recreate API which isn't working so well.

**Comment by rpgreen** [comment]
Fixed. Thanks for reporting

**Comment by cosbor11** [comment]
It looks like emma's fix was applied to a bbc fork. Was this fix applied to a release?

**Comment by cosbor11** [comment]
I confirmed that this issue still occurs in the master branch and has not been merged. I think that the release 1.0.1 should be hotfixed to have this critical bugfix.

**Comment by rpgreen** [comment]
Are you referring to the maven release? Can you post swagger to reproduce?

**Comment by cosbor11** [comment]
Sure. 

I think that her fix was applied. I cloned master and saw her changes..
But I am probably just having a similar bug. 

**Here is the swagger file I am using:**

```
    {
    "swagger": "2.0",
    "info": {
        "version": "0.7.0",
        "title": "event-gateway",
        "contact": {
            "name": "RCLON API Team",
            "url": "http://ebates.com"
        }
    },
    "basePath": "/",
    "schemes": [
        "https"
    ],
    "paths": {
        "/amex-card-auth-events": {
            "post": {
                "tags": [
                    "AuthTransactions"
                ],
                "summary": "Endpoint to receive AmexCardAuthEvents",
                "consumes": [],
                "produces": [],
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AmexCardAuthEvent"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/AmexResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/AmexResponse"
                        }
                    }
                }
            }
        },
        "/mastercard-card-auth-events": {
            "post": {
                "tags": [
                    "AuthTransactions"
                ],
                "summary": "Endpoint to receive MasterCardAuthEvents",
                "consumes": [],
                "produces": [],
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/MasterCardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/MasterCardResponse"
                        }
                    }
                }
            }
        },
        "/visa-card-auth-events": {
            "post": {
                "tags": [
                    "AuthTransactions"
                ],
                "summary": "Endpoint to receive VisaCardTransactionEventMaps",
                "consumes": [],
                "produces": [],
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/VisaCardTransactionEventMap"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/VisaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/VisaResponse"
                        }
                    }
                }
            }
        },
        "/visa-settlement-events": {
            "post": {
                "tags": [
                    "SettlementOperations"
                ],
                "summary": "Endpoint to receive VisaCardTransactionEventMaps",
                "consumes": [],
                "produces": [],
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/VisaCardTransactionEventMap"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/VisaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/VisaResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AmexCardAuthEvent": {
          "required": [
            ],
            "properties": {
                "transaction_time": {
                    "type": "string"
                },
                "transaction_id": {
                    "type": "string"
                },
                "offer_id": {
                    "type": "string"
                },
                "cm_alias": {
                    "type": "string"
                },
                "merchant_number": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        },
        "VisaCardTransactionEventMap": {
          "required": [
            ],
            "properties": {
                "CardId": {
                    "type": "string"
                },
                "ExternalUserId": {
                    "type": "string"
                },
                "MessageElementsCollection": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/KeyValuePair"
                    }
                },
                "MessageId": {
                    "type": "string"
                },
                "MessageName": {
                    "type": "string"
                },
                "UserDefinedFieldsCollection": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/KeyValuePair"
                    }
                },
                "UserProfileId": {
                    "type": "string"
                }
            }
        },
        "KeyValuePair": {
            "required": [
                "Value",
                "Key"
            ],
            "properties": {
                "Value": {
                    "type": "string"
                },
                "Key": {
                    "type": "string"
                }
            }
        },
        "VisaResponse": {
            "required": [
                "status_code",
                "error_msg"
            ],
            "properties": {
                "status_code": {
                    "type": "integer",
                    "format": "int32"
                },
                "error_msg": {
                    "type": "string"
                }
            }
        },
        "AmexResponse": {
            "required": [
                "status_code",
                "error_msg"
            ],
            "properties": {
                "status_code": {
                    "type": "integer",
                    "format": "int32"
                },
                "error_msg": {
                    "type": "string"
                }
            }
        },
        "MasterCardResponse": {
            "required": [
                "status_code",
                "error_msg"
            ],
            "properties": {
                "status_code": {
                    "type": "integer",
                    "format": "int32"
                },
                "error_msg": {
                    "type": "string"
                }
            }
        }
    }
}
```

**Here is the command I am running:**

```
API_ID=$(aws apigateway get-rest-apis --query "items[?name == '${API_NAME}'] | [0].{id: id}" --output text)
    $IMPORTER_TOOL/aws-api-import.sh --update "$API_ID" "$SWAGGER_FILE"
```

**And here is the log/error:**

```
    2016-02-09 14:02:41,562 INFO - Using API Gateway endpoint https://apigateway.us-west-2.amazonaws.com
2016-02-09 14:02:42,683 INFO - Attempting to update API from Swagger definition. API identifier: yvytj7fuz5 Swagger file: src/main/resources/swagger/v1/swagger.json
reading from src/main/resources/swagger/v1/swagger.json
2016-02-09 14:02:42,760 INFO - Parsed Swagger with 4 paths
2016-02-09 14:02:43,074 INFO - Updating model for api id yvytj7fuz5 and model name AmexCardAuthEvent
2016-02-09 14:02:43,217 INFO - Generated json-schema for model AmexCardAuthEvent: {"properties":{"transaction_time":{"type":"string"},"transaction_id":{"type":"string"},"offer_id":{"type":"string"},"cm_alias":{"type":"string"},"merchant_number":{"type":"integer","format":"int64"}},"definitions":{}}
2016-02-09 14:02:43,591 INFO - Updating model for api id yvytj7fuz5 and model name VisaCardTransactionEventMap
2016-02-09 14:02:43,602 INFO - Generated json-schema for model VisaCardTransactionEventMap: {"properties":{"CardId":{"type":"string"},"ExternalUserId":{"type":"string"},"MessageElementsCollection":{"type":"array","items":{"$ref":"#/definitions/KeyValuePair"}},"MessageId":{"type":"string"},"MessageName":{"type":"string"},"UserDefinedFieldsCollection":{"type":"array","items":{"$ref":"#/definitions/KeyValuePair"}},"UserProfileId":{"type":"string"}},"definitions":{"KeyValuePair":{"required":["Key","Value"],"properties":{"Value":{"type":"string"},"Key":{"type":"string"}}}}}
2016-02-09 14:02:43,938 INFO - Updating model for api id yvytj7fuz5 and model name KeyValuePair
2016-02-09 14:02:43,945 INFO - Generated json-schema for model KeyValuePair: {"required":["Key","Value"],"properties":{"Value":{"type":"string"},"Key":{"type":"string"}},"definitions":{}}
2016-02-09 14:02:44,163 INFO - Updating model for api id yvytj7fuz5 and model name VisaResponse
2016-02-09 14:02:44,168 INFO - Generated json-schema for model VisaResponse: {"required":["error_msg","status_code"],"properties":{"status_code":{"type":"integer","format":"int32"},"error_msg":{"type":"string"}},"definitions":{}}
2016-02-09 14:02:44,465 INFO - Updating model for api id yvytj7fuz5 and model name AmexResponse
2016-02-09 14:02:44,469 INFO - Generated json-schema for model AmexResponse: {"required":["error_msg","status_code"],"properties":{"status_code":{"type":"integer","format":"int32"},"error_msg":{"type":"string"}},"definitions":{}}
2016-02-09 14:02:44,693 INFO - Updating model for api id yvytj7fuz5 and model name MasterCardResponse
2016-02-09 14:02:44,697 INFO - Generated json-schema for model MasterCardResponse: {"required":["error_msg","status_code"],"properties":{"status_code":{"type":"integer","format":"int32"},"error_msg":{"type":"string"}},"definitions":{}}
2016-02-09 14:02:45,164 INFO - Updating method for api id yvytj7fuz5 and resource yuxg7f and method post
2016-02-09 14:02:45,599 INFO - Creating method response for api yvytj7fuz5 and method POST and status 200
2016-02-09 14:02:45,664 INFO - Found reference to existing model AmexResponse
2016-02-09 14:02:45,788 INFO - Creating method response for api yvytj7fuz5 and method POST and status 400
2016-02-09 14:02:45,903 INFO - Found reference to existing model AmexResponse
2016-02-09 14:02:46,200 INFO - Updating method for api id yvytj7fuz5 and resource wm09tw and method post
2016-02-09 14:02:46,636 INFO - Creating method response for api yvytj7fuz5 and method POST and status 200
2016-02-09 14:02:46,703 INFO - Found reference to existing model MasterCardResponse
2016-02-09 14:02:46,833 INFO - Creating method response for api yvytj7fuz5 and method POST and status 400
2016-02-09 14:02:46,955 INFO - Found reference to existing model MasterCardResponse
2016-02-09 14:02:47,247 INFO - Updating method for api id yvytj7fuz5 and resource fv4tgp and method post
2016-02-09 14:02:47,690 INFO - Creating method response for api yvytj7fuz5 and method POST and status 200
2016-02-09 14:02:47,758 INFO - Found reference to existing model VisaResponse
2016-02-09 14:02:47,888 INFO - Creating method response for api yvytj7fuz5 and method POST and status 400
2016-02-09 14:02:48,002 INFO - Found reference to existing model VisaResponse
2016-02-09 14:02:48,344 INFO - Updating method for api id yvytj7fuz5 and resource i2c16z and method post
2016-02-09 14:02:48,815 INFO - Creating method response for api yvytj7fuz5 and method POST and status 200
2016-02-09 14:02:48,891 INFO - Found reference to existing model VisaResponse
2016-02-09 14:02:49,050 INFO - Creating method response for api yvytj7fuz5 and method POST and status 400
2016-02-09 14:02:49,182 INFO - Found reference to existing model VisaResponse
2016-02-09 14:02:49,310 INFO - Cleaning up removed methods
2016-02-09 14:02:49,780 INFO - Cleaning up removed resources
2016-02-09 14:02:49,950 INFO - Removing deleted model modelc3eb9838
2016-02-09 14:02:50,101 ERROR - Error importing API definition
com.amazonaws.services.apigateway.model.ConflictException: Cannot delete model 'modelc3eb9838', is referenced in method request: /mastercard-card-auth-events/POST (Service: null; Status Code: 409; Error Code: null; Request ID: dc131039-cf78-11e5-85b9-27dd269e9bf6)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1307)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:894)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
    at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
    at com.amazonaws.hal.client.HalClient.deleteResource(HalClient.java:142)
    at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:129)
    at com.sun.proxy.$Proxy32.deleteModel(Unknown Source)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.lambda$cleanupModels$2(ApiGatewaySdkApiImporter.java:167)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter$$Lambda$9/16373883.accept(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.cleanupModels(ApiGatewaySdkApiImporter.java:165)
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateApi(ApiGatewaySdkSwaggerApiImporter.java:92)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.updateApi(ApiGatewaySwaggerFileImporter.java:58)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.importSwagger(ApiImporterMain.java:161)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:145)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
```

**Comment by cosbor11** [comment]
It is because of the following swagger part:

```
    "parameters": [
    {
        "in": "body",
        "name": "body",
        "required": true,
        "schema": {
            "type": "string"
        }
    }
]
```

I have a body parameter with `type=string`. 

Unfortunately, I do need to support this in my body because of my integration with MasterCard.

**Comment by rpgreen** [comment]
This looks like a bug related to using 

```
"schema": {
   "type": "string"
}"
```

Does it work if you change this to a $ref'd schema under definitions? Similar to the other models?

**Comment by cosbor11** [comment]
Unfortunately, I dont have enough leverage with MasterCard to tell them to send their POST requests in any other format

**Comment by rpgreen** [comment]
I'm not asking you to change your API - that would be unreasonable.

Does it work if you do this?

```
"schema": {
    "$ref": "#/definitions/MasterCardRequest"
}

...
 "MasterCardRequest": {
   "type" : "string"
}
```

Alternatively you may be able to omit the request model altogether

**Comment by cosbor11** [comment]
hey, thanks for your help btw..
I did try that. And it is able to create it by name with the same config.  (I had to delete the old api before creating it)

On a somewhat related note: It seems that the importer does not support changing a Definition name.  It throws an the same error because it wont allow you to delete and throws the same error message. 

**_so for example, I had:**_

```
"schema": {
    "$ref": "#/definitions/StringRequest"
}
...
"StringRequest": {
   "type" : "string"
}
```

**_Then changed it to:**_

```
"schema": {
"$ref": "#/definitions/MasterCardRequest"
}
...
"MasterCardRequest": {
      "type" : "string"
 }
```

**and it threw:** Cannot delete model 'StringRequest' error.

I may have to delete, then create the whole api rather than use the --update option for now anyways.
